const CACHE = "jp-tutor-v85";
const ASSETS = [
  "./",
  "./index.html",
  "./app.js",
  "./style.css",
  "./manifest.json",
  "./icon-192.png",
  "./icon-512.png",
  "./data/vocab.json",
  "./data/grammar.json",
  "./data/quiz.json",
  "./data/vocab_ko.json",
  "./data/grammar_ko.json",
  "./data/quiz_ko.json",
  "./data/scenes_topik01.json",
  "./data/scenes_topik02.json",
  "./data/scenes_topik03.json",
  "./data/scenes_topik04.json",
  "./data/scenes_topik05.json",
  "./data/scenes_topik06.json",
  "./data/scenes_topik07.json",
  "./data/scenes_topik08.json",
  "./data/scenes_topik09.json",
  "./data/scenes_topik10.json",
  "./data/scenes_topik11.json",
  "./data/scenes_topik12.json",
  "./data/scenes_topik13.json",
  "./data/scenes_topik14.json",
  "./data/scenes_topik15.json",
  "./data/scenes_topik16.json",
  "./data/scenes_topik17.json",
  "./data/scenes_topik18.json",
  "./data/scenes_topik19.json",
  "./data/scenes_topik20.json",
  "./data/scenes_topik21.json",
  "./data/scenes_topik22.json",
  "./data/scenes_topik23.json",
  "./data/scenes_topik24.json",
  "./data/scenes_topik25.json",
  "./data/scenes_topik26.json",
  "./data/scenes_topik27.json",
  "./data/scenes_topik28.json",
  "./data/scenes_topik29.json",
  "./data/scenes_topik30.json",
  "./data/scenes_topik31.json",
  "./data/scenes_topik32.json",
  "./data/scenes_topik33.json",
  "./data/scenes_topik34.json",
  "./data/scenes_topik35.json",
  "./data/scenes_topik36.json",
  "./data/scenes_topik37.json",
  "./data/scenes_topik38.json",
  "./data/scenes_topik39.json",
  "./data/scenes_topik40.json",
  "./data/scenes_topik41.json",
  "./data/scenes_topik42.json",
  "./data/scenes_topik43.json",
  "./data/scenes_topik44.json",
  "./data/scenes_topik45.json",
  "./data/scenes_topik46.json",
  "./data/scenes_topik47.json",
  "./data/scenes_topik48.json",
  "./data/scenes_topik49.json",
  "./data/scenes_topik50.json",
  "./data/scenes_topik51.json",
  "./data/scenes_topik52.json",
  "./data/scenes_topik53.json",
  "./data/scenes_topik54.json",
  "./data/scenes_topik55.json",
  "./data/scenes_topik56.json",
  "./data/scenes_topik57.json",
  "./data/scenes_topik58.json",
  "./data/scenes_topik59.json",
  "./data/scenes_topik60.json",
  "./data/scenes_topik61.json",
  "./data/scenes_topik62.json",
  "./data/scenes_topik63.json",
  "./data/scenes_topik64.json",
  "./data/scenes_topik65.json",
  "./data/scenes_topik66.json",
  "./data/scenes_topik67.json",
  "./data/scenes_topik68.json",
  "./data/scenes_topik69.json",
  "./data/scenes_topik70.json",
  "./data/scenes_topik71.json",
  "./data/scenes_topik72.json",
  "./data/scenes_topik73.json",
  "./data/scenes_topik74.json",
  "./data/scenes_topik75.json",
  "./data/scenes_topik76.json",
  "./data/scenes_topik77.json",
  "./data/scenes_topik78.json",
  "./data/scenes_topik79.json",
  "./data/scenes_topik80.json",
  "./data/scenes_topik81.json",
  "./data/scenes_topik82.json",
  "./data/scenes_topik83.json",
  "./data/scenes_jap001.json",
  "./data/scenes_jap002.json",
  "./data/scenes_jap003.json",
  "./data/scenes_jap004.json",
  "./data/scenes_jap005.json",
  "./data/scenes_jap006.json",
  "./data/scenes_jap007.json",
  "./data/scenes_jap008.json",
  "./data/scenes_jap009.json",
  "./data/scenes_jap010.json",
  "./data/scenes_jap011.json",
  "./data/scenes_jap012.json",
  "./data/scenes_jap013.json",
  "./data/scenes_jap014.json",
  "./data/scenes_jap015.json",
  "./data/scenes_jap016.json",
  "./data/scenes_jap017.json",
  "./data/scenes_jap018.json",
  "./data/scenes_jap019.json",
  "./data/scenes_jap020.json",
  "./data/scenes_jap021.json",
  "./data/scenes_jap022.json",
  "./data/scenes_jap023.json",
  "./data/scenes_jap024.json",
  "./data/scenes_jap025.json",
  "./data/scenes_jap026.json",
  "./data/scenes_jap027.json",
  "./data/scenes_jap028.json",
  "./data/scenes_jap029.json",
  "./data/scenes_jap030.json",
  "./data/scenes_jap031.json",
  "./data/scenes_jap032.json",
  "./data/scenes_jap033.json",
  "./data/scenes_jap034.json",
  "./data/scenes_jap035.json",
  "./data/scenes_jap036.json",
  "./data/scenes_jap037.json",
  "./data/scenes_jap038.json",
  "./data/scenes_jap039.json",
  "./data/scenes_jap040.json",
  "./data/scenes_jap041.json",
  "./data/scenes_jap042.json",
  "./data/scenes_jap043.json",
  "./data/scenes_jap044.json",
  "./data/scenes_jap045.json",
  "./data/scenes_jap046.json",
  "./data/scenes_jap047.json",
  "./data/scenes_jap048.json",
  "./data/scenes_jap049.json",
  "./data/scenes_jap050.json",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(resp => {
        const copy = resp.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return resp;
      }).catch(() => cached);
    })
  );
});
